apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "content-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-api.labels" . | nindent 4 }}
automountServiceAccountToken: false
