apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: content-api-k3d
helmGlobals:
  chartHome: ../../deploy
helmCharts:
  - name: content-api
    releaseName: content-api-k3d
    namespace: content-api-k3d
    valuesFile: ../../deploy/content-api/values.yaml
    additionalValuesFiles:
      - values.yaml
    includeCRDs: false
